_target_: cdvae.pl_modules.decoder.GemNetTDecoder
hidden_dim: 128
latent_dim: ${model.latent_dim}
max_neighbors: ${model.max_neighbors}
radius: ${model.radius}
scale_file: /workspace/inorganic_SEEs-1/generator/CDVAE/cdvae/pl_modules/gemnet/gemnet-dT.json
